# https://wiki.hypr.land/Configuring/Variables/
# https://wiki.hypr.land/Configuring/Variables/#general
# https://wiki.hypr.land/Configuring/Variables/#decoration
# https://wiki.hypr.land/Configuring/Tearing/

    #################
    # LOOK AND FEEL #
    #################
    general {
    # Gaps
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    # Border
    col.active_border = rgba(e6f2ff40) rgba(ffffff00) 140deg
    col.inactive_border = rgba(ffffff00)
    resize_on_border = false # Set to true enable resizing windows by clicking and dragging on borders and gaps
    # Tearing
    allow_tearing = false
    # Layout
    layout = dwindle
    }

    decoration {
    # Window / Layout
    rounding = 0
    rounding_power = 0
    active_opacity = 1.0
    inactive_opacity = 0.8
        shadow {
        enabled = false
        range = 1
        render_power = 0
        color = rgba(ffffffff)
        }
        blur {
        enabled = true
        size = 3
        passes = 3
        vibrancy = 0
        }
    }

    dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true
    }

    master {
    allow_small_split = true
    special_scale_factor = 1
    mfact = 0.58
    new_status = slave # Or master
    new_on_top =  false
    new_on_active = after
    orientation = left
    slave_count_for_center_master = 2
    center_master_fallback = left
    smart_resizing = true
    drop_at_cursor = false
    always_keep_position = false
    }

    misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    }
