# GENERAL
general {
    # Ocultar el cursor mientras la pantalla está bloqueada.
    hide_cursor = true
    # Evita la barra de carga de hyprlock al iniciarse.
    disable_loading_bar = true
    # No permitir desbloqueo accidental con entrada vacía.
    ignore_empty_input = false
}
# FONDO
background {
    monitor =
    # Captura el escritorio actual y lo utiliza como fondo.
    path = screenshot
    color = rgba(17, 17, 17, 1.0)
    blur_passes = 3
    blur_size = 3

    # Mantener el fondo relativamente natural.
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.0
    vibrancy_darkness = 0.05
}
# RELOJ
label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    font_family = Sans
    halign = center
    valign = center
    position = 0, 80
    shadow_passes = 0
}
# FECHA
label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %B %d')"
    color = rgba(255, 255, 255, 0.75)
    font_size = 18
    font_family = Sans
    halign = center
    valign = center
    position = 0, 10
    shadow_passes = 0
}
# USUARIO
label {
    monitor =
    text = $USER
    color = rgba(255, 255, 255, 0.9)
    font_size = 18
    font_family = Inter
    halign = center
    valign = center
    position = 0, -80
    shadow_passes = 0
}
# CAMPO DE CONTRASEÑA
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.35)
    inner_color = rgba(0, 0, 0, 0.35)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    placeholder_text = <i>Contraseña...</i>
    hide_input = false
    halign = center
    valign = center
    position = 0, -150
}
