general {
    # Evita iniciar varias instancias de hyprlock.
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    # Reactivar el display después de volver de suspensión.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
    inhibit_sleep = 2
}
# BRILLO
listener {
    # 5 minutos sin actividad.
    timeout = 300
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}
# BLOQUEO
listener {
    # 10 minutos sin actividad.
    timeout = 600
    on-timeout = loginctl lock-session
}
# APAGAR PANTALLA
listener {
    # 10 minutos y 30 segundos.
    timeout = 630
    # Apagar los displays mediante DPMS.
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    # Volver a encenderlos cuando detectemos actividad.
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}
# SUSPENSIÓN
listener {
    # 30 minutos sin actividad.
    timeout = 1800
    on-timeout = systemctl suspend
}
