-- Imports
require("binds")
require("input")
require("custom")
require("animation")
require("rules")
-- Watch windows (Dwindle, Master, Scroll, ETC)
hl.config({
    autogenerated = 0,
})
-- Monitors
hl.monitor({
  output = "eDP-1",
  mode = "1920x1080@60",
  position = "auto",
  scale = 1,
})
-- AutoStart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("copyq")
    hl.exec_cmd("mpd")
    hl.exec_cmd("sleep 2 && bash ~/.config/hypr/scripts/wallpaper.sh")
    hl.exec_cmd("sleep 2 && bash ~/.config/hypr/scripts/notefications.sh")
end)
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
