-- Import
require("binds")
require("input")
require("custom")
require("animation")
require("rules")

-- Remove warning
hl.config({
    autogenerated = 0,
})

-- Monitors
hl.monitor({
  output = "eDP-1",
  mode = "1920x1080@60",
  position = "auto",
  scale = 1,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    cm = "auto",
    position = "auto",
    scale = 1,
    mirror = "eDP-1",
})

-- AutoStart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("sleep 5 && waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("copyq")
    hl.exec_cmd("mpd")
    hl.exec_cmd("sleep 2 && bash ~/.config/hypr/scripts/wallpaper.sh")
    hl.exec_cmd("sleep 2 && bash ~/.config/hypr/scripts/notefications.sh")
end)

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME","qt6ct")
