    # https://wiki.hypr.land/Configuring/Variables/#input
    # https://wiki.hypr.land/Configuring/Variables/#cursor
    # https://wiki.hypr.land/Configuring/Variables/#gestures
    # https://wiki.hypr.land/Configuring/Gestures/
    # https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs

    ###################
    # INPUT / DEVICES #
    ###################
    # Keyboard
    input {
    kb_layout = us,es
    kb_variant =
    kb_model =
    kb_options = grp:alt_space_toggle
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    # Touchpad
    touchpad {
    natural_scroll = true
    }
    }
    # Cursor
    cursor {
    inactive_timeout = 1
    }
    # Mouse
    device {
    name = epic-mouse-v1
    sensitivity = -0.5
    }
    # Gestures
    # gesture = fingers, direction, action, options
    gesture = 3, horizontal, workspace
    gesture = 3, up, close
    gesture = 3, down, dispatcher, exec, kitty
    gesture = 2, pinchin, dispatcher, movetoworkspace, special:magic
    gesture = 2, pinchout, dispatcher, togglespecialworkspace, magic
    gesture = 3, pinchout, dispatcher, movetoworkspace, +0
    gesture = 3, pinchin, dispatcher, exec, kitty -e yazi
    gesture = 4, up, dispatcher, exec, rofi -show drun
    gesture = 4, down, dispatcher, exec, ~/.config/rofi/scripts/r_wallpaper/wallpaper-rofi.sh
    gesture = 4, left, dispatcher, exec, ~/.config/rofi/scripts/r_menu/quickmenu.sh
    gesture = 4, right, dispatcher, exec, ~/.config/rofi/scripts/r_remember/rem-picker.sh
